% This script trains the neural network for predicting throttle and brake.
% In order to run it, you first should have the neural_net_data.mat file in
% this directory, generated by the generate_dataset.m script.
%
% After training is done, this script plots the predicted and ground-truth
% brake and throttle at each time-step, for all experiments used.
%
% NOTE: The train function used here automatically separates the dataset
% into validation and training parts, randomly. The plot is shown for all
% the points, regardless of whether they were used in training or not (a
% possible improvement of this script would be to only plot for the
% validation subset, or for a held-out subset of data).

clear; clc;
rng(1);

% Load dataset and create network
load('neural_net_data.mat');
net = feedforwardnet([10 10]);

% Train
[net,tr]= train(net,inputs,targets);

preds = net(inputs);

ax1 = subplot(3,1,1);
plot(targets(1,:),'b');
hold on;
plot(preds(1,:),'b--');
title Throttle
axis([0 inf -0.1 1.1]);

ax2 = subplot(3,1,2);
plot(targets(2,:),'r');
hold on;
plot(preds(2,:),'r--');
title Brake
axis([0 inf -0.1 1.1]);

ax3 = subplot(3,1,3);
plot(inputs(1,:));
yyaxis right
plot(inputs(2,:));
legend a v
title 'First and second inputs'

linkaxes([ax1, ax2, ax3], 'x');

save net net;